/**
 * Words the sample may keep verbatim because they are field labels, not personal data (R8): the
 * labels printed next to the figures the existing parsers read, plus common German payroll terms.
 * Entries are normalised (see {@link normalizeLabelWord}), alphabetical, and contain no digits —
 * a word with a digit is a value and is replaced, never kept. Names, addresses and unknown words
 * are deliberately absent: they always need an explicit user decision.
 */
const LABELS = [
  'abr',
  'abzüge',
  'ag',
  'ag-zuschuss',
  'akt',
  'aktien',
  'altersvorsorge',
  'anteil',
  'arbeitgeber',
  'arbeitgeberanteil',
  'arbeitgeberzuschuss',
  'arbeitnehmer',
  'arbeitnehmeranteil',
  'arbeitnehmerbeiträge',
  'arbeitnehmers',
  'arbeitslohn',
  'arbeitslosenversicherung',
  'aus',
  'ausgleichsbeträge',
  'auszahlung',
  'auszahlungsbetrag',
  'auszuzahlender',
  'av',
  'bankleitzahl',
  'be-/abzüge',
  'beitrag',
  'beiträge',
  'besteuerte',
  'besteuerter',
  'betrag',
  'bezüge',
  'bonus',
  'brutto',
  'bruttoarbeitslohn',
  'bruttobezüge',
  'der',
  'des',
  'dienstgrad',
  'dienstmonat',
  'differenz',
  'einbehaltene',
  'einbehaltener',
  'einmalbezug',
  'einmalbezüge',
  'einschl',
  'elsg',
  'entgelt',
  'entgeltbestandteile',
  'entgeltnachweis',
  'entschädigungen',
  'ermäßigt',
  'euro',
  'firmenzahler',
  'freibetrag',
  'funktionszulage',
  'für',
  'gehalt',
  'geldwerter',
  'gesamt',
  'gesamt-brut',
  'gesamtbrutto',
  'gesetzl',
  'gesetzliche',
  'gesetzlichen',
  'hinfahrt',
  'iban',
  'inland',
  'jahr',
  'jahressumme',
  'jahressummen',
  'jobticket',
  'kinderfreibetrag',
  'kirchensteuer',
  'konfession',
  'krankenkasse',
  'krankenversicherung',
  'kv',
  'kv-beitrag',
  'letzt',
  'lfd',
  'lohn',
  'lohnst',
  'lohnsteuer',
  'lohnsteuerbescheinigung',
  'manueller',
  'matchingaktien',
  'mobilitätszuschlag',
  'monat',
  'nachverrechnung',
  'netto',
  'nettoentgelt',
  'ohne',
  'pausch',
  'pflegeversicherung',
  'prämie',
  'pv',
  'pv-beitrag',
  'reisekostenvergütung',
  'rentenversicherung',
  'rückfahrt',
  'rv',
  'sachbezüge',
  'seite',
  'solidaritätszuschlag',
  'solizuschlag',
  'solz',
  'sonderabgabe',
  'sonderzahlung',
  'sonderzuwendung',
  'sonstige',
  'sonstiger',
  'sozialen',
  'st-/sv-frei',
  'stb',
  'steuer',
  'steuer-brutto',
  'steuerfreie',
  'steuerklasse',
  'summe',
  'sv-brutto',
  'tarifgehalt',
  'überweisung',
  'umlage',
  'und',
  'verpflegungsgeld',
  'vl',
  'von',
  'vorm',
  'vorteil',
  'wehrsold',
  'wehrsoldgruppe',
  'zulage',
  'zum',
  'zur',
  'zuschlag',
  'zuschuss',
  'zuschüsse',
];

const EDGE_PUNCTUATION = new Set('.,;:()[]*"\'|');

const isEdge = (char: string): boolean => EDGE_PUNCTUATION.has(char) || char.trim() === '';

/** Lower-case, with surrounding punctuation (`:`, `,`, `.`, brackets, `*`, quotes) stripped. */
export function normalizeLabelWord(word: string): string {
  const chars = [...word.toLowerCase()];
  let start = 0;
  let end = chars.length;
  while (start < end && isEdge(chars[start])) start += 1;
  while (end > start && isEdge(chars[end - 1])) end -= 1;
  return chars.slice(start, end).join('');
}

export const LABEL_VOCABULARY: ReadonlySet<string> = new Set(LABELS);

/** True when the word (case and surrounding punctuation ignored) is a known payroll label. */
export function isKnownLabel(word: string): boolean {
  const normalized = normalizeLabelWord(word);
  return normalized !== '' && !/\d/.test(normalized) && LABEL_VOCABULARY.has(normalized);
}
